openapi: 3.0.3

info:
  version: "1"
  title: "Food delivery API"
  description: "Demo Food delivery API"

paths:
  # Restaurant
  /restaurant:
    post:
      summary: Create
      operationId: createRestaurant
      tags:
        - Restaurant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantRequestBody"
      responses:
        200:
          description: Restaurant Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantSchema"
    get:
      summary: Get Restaurants
      operationId: getRestaurants
      tags:
        - Restaurant
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
          example: 0
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
          example: 10
      responses:
        200:
          description: Restaurants Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantsResponse"
    delete:
      summary: Delete all Restaurants
      tags:
        - Restaurant
      operationId: deleteAllRestaurants
      responses:
        204:
          description: Success
  /restaurant/{id}:
    patch:
      summary: Update
      operationId: updateRestaurantById
      tags:
        - Restaurant
      parameters:
        - name: id
          in: path
          description: Restaurant ID
          required: true
          schema:
            type: number
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantRequestBody"
      responses:
        200:
          description: Restaurant Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantSchema"
    get:
      summary: Get Restaurant by ID
      operationId: getRestaurantById
      tags:
        - Restaurant
      parameters:
        - name: id
          in: path
          description: Restaurant ID
          required: true
          schema:
            type: number
          example: 1
      responses:
        200:
          description: Restaurant Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantSchema"
    delete:
      summary: Delete Restaurant by ID
      tags:
        - Restaurant
      operationId: deleteOneRestaurant
      parameters:
        - name: id
          in: path
          description: Restaurant ID
          required: true
          schema:
            type: number
          example: 1
      responses:
        204:
          description: Success
  # END Restaurant

  # Courier
  /courier:
    post:
      summary: Create
      operationId: createCourier
      tags:
        - Courier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourierRequestBody"
      responses:
        200:
          description: Courier Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourierSchema"
    get:
      summary: Get Couriers
      operationId: getCouriers
      tags:
        - Courier
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
          example: 0
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
          example: 10
      responses:
        200:
          description: Couriers Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CouriersResponse"
    delete:
      summary: Delete all Couriers
      tags:
        - Courier
      operationId: deleteAllCouriers
      responses:
        204:
          description: Success
  /courier/{id}:
    patch:
      summary: Update
      operationId: updateCourierById
      tags:
        - Courier
      parameters:
        - name: id
          in: path
          description: Courier ID
          required: true
          schema:
            type: number
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourierRequestBody"
      responses:
        200:
          description: Courier Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourierSchema"
    get:
      summary: Get Courier by ID
      operationId: getCourierById
      tags:
        - Courier
      parameters:
        - name: id
          in: path
          description: Courier ID
          required: true
          schema:
            type: number
          example: 1
      responses:
        200:
          description: Courier Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourierSchema"
    delete:
      summary: Delete Courier by ID
      tags:
        - Courier
      operationId: deleteOneCourier
      parameters:
        - name: id
          in: path
          description: Courier ID
          required: true
          schema:
            type: number
          example: 1
      responses:
        204:
          description: Success
  # END Courier

  # Product
  /product:
    post:
      summary: Create
      operationId: createProduct
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductRequestBody"
      responses:
        200:
          description: Product Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSchema"
    get:
      summary: Get Products
      operationId: getProducts
      tags:
        - Product
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
          example: 0
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
          example: 10
      responses:
        200:
          description: Products Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductsResponse"
    delete:
      summary: Delete all Products
      tags:
        - Product
      operationId: deleteAllProducts
      responses:
        204:
          description: Success
  /product/{id}:
    patch:
      summary: Update
      operationId: updateProductById
      tags:
        - Product
      parameters:
        - name: id
          in: path
          description: Product ID
          required: true
          schema:
            type: number
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductRequestBody"
      responses:
        200:
          description: Product Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSchema"
    get:
      summary: Get Product by ID
      operationId: getProductById
      tags:
        - Product
      parameters:
        - name: id
          in: path
          description: Product ID
          required: true
          schema:
            type: number
          example: 1
      responses:
        200:
          description: Product Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSchema"
    delete:
      summary: Delete Product by ID
      tags:
        - Product
      operationId: deleteOneProduct
      parameters:
        - name: id
          in: path
          description: Product ID
          required: true
          schema:
            type: number
          example: 1
      responses:
        204:
          description: Success
  # END Product

components:
  schemas:
    RestaurantSchema:
      description: Restaurant schema
      type: object
      required:
        - id
        - name
        - picture
        - created_at
        - updated_at
      properties:
        id:
          type: number
        name:
          type: string
        picture:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      example:
        id: 1
        name: Some Restaurant
        picture: some_pic_restaurant
        created_at: '2020-02-10 17:32:28'
        updated_at: '2020-02-10 17:32:28'
    RestaurantRequestBody:
      description: Create Restaurant
      type: object
      required:
        - name
        - picture
      properties:
        name:
          type: string
        picture:
          type: string
      example:
        name: Some Restaurant
        picture: some_pic_restaurant
    RestaurantsResponse:
      description: List of Restaurants
      type: array
      items:
        $ref: '#/components/schemas/RestaurantSchema'

    CourierSchema:
      description: Courier schema
      type: object
      required:
        - id
        - name
        - created_at
        - updated_at
      properties:
        id:
          type: number
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      example:
        id: 1
        name: Some Courier
        created_at: '2020-02-10 17:32:28'
        updated_at: '2020-02-10 17:32:28'
    CourierRequestBody:
      description: Create Courier
      type: object
      required:
        - name
      properties:
        name:
          type: string
      example:
        name: Some Courier
    CouriersResponse:
      description: List of Couriers
      type: array
      items:
        $ref: '#/components/schemas/CourierSchema'

    ProductSchema:
      description: Product schema
      type: object
      required:
        - id
        - name
        - price
        - description
        - restaurant_id
        - picture
        - created_at
        - updated_at
      properties:
        id:
          type: number
        name:
          type: string
        price:
          type: number
        description:
          type: string
        picture:
          type: string
        restaurant_id:
          type: number
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      example:
        id: 1
        name: Some Product
        created_at: '2020-02-10 17:32:28'
        updated_at: '2020-02-10 17:32:28'
    ProductRequestBody:
      description: Create Product
      type: object
      required:
        - name
      properties:
        name:
          type: string
      example:
        name: Some Product
        price: 100.01
        description: Some product description
        restaurant_id: 1
        picture: some_pic_product
    ProductsResponse:
      description: List of Products
      type: array
      items:
        $ref: '#/components/schemas/ProductSchema'
